config/routes.rb
Momento::Application.routes.draw do
  get "users/index"
  get "users/new"
  get "welcome/index"

  
    resources :users

    root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :image, styles: { small: "64*64", med: "100*100", large: "200*200"}
	# validates :email, :name,  :presence => true, :avatar, :attachment_presence=> true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@user= User.all
  end

  def show
  	@user= User.find(params[:id])
  end

  def new
  	@user= User.new
  end

  def edit
  end

  def create
  	@user= User.new(user_params)

  	if @user.save
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def update
  end

  def destroy
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :name, :image)
  	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Momento</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, html: {multipart: true} do |f| %>


<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this account from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= f.label :email %> <br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :name %> <br>
  <%= f.text_area :name %>
</p>

<p>
  <%= f.file_field :image %>
</p>

 <!-- <%= link_to image_tag(@user.image.url(:med)), @user.image.url %> -->

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/users/index.html.erb
<h1> List of Accounts with momento: </h1>

<%= link_to 'New Account', new_user_path %>

<table>
	<tr>
		<th> Name </th>
		<th> Email </th>
		<th colspan="5"></th>
	</tr>


<% if @user.blank? %> 
<% else %>
	<% for user in @user %>
	<tr>	
  	<td> Name: <%= user.name %> </td>
  	<td> Email id: <%= user.email %> </td>
  	<td><%= link_to 'Show', user_path(user) %></td>
  </tr>
    
   <% end %>
  
<% end %>
</table>

app/views/users/new.html.erb
<h1> New Account </h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.css.erb
html { 
 
	 background: url(<%= @user.image.url %>) no-repeat center center fixed; 
}

app/views/users/show.html.erb
 <%= stylesheet_link_tag   user_path(@user, format: :css), media: "all" %>
<p> 
	Name: 
	<%= @user.name %>
	<%= @user.id%>
</p>



<%= link_to 'Home', users_path %>

	
<h1> DISPLAY WEATHER <H1>

<h1> DISPLAY QUOTE <H1>

app/views/welcome/index.html.erb
<h1> List of Accounts with momento: </h1>

<%= <% if @user.blank? %>
  <% for |user| in @user %>
  	Name of user: <%= u.name %>
    
   <% end %>
<% else %>
  
<% end %>